### ISSUE TITLE
GPT type T5  impementation

### ISSUE THREAD

**Issue by aamir-gmail** [lucidrains/CoLT5-attention#2]
Great work, is there a guide or implementation for either GPT or T5 type models?

**Comment by lucidrains** [comment]
the paper never presented a solution for decoders, only the encoder side

i may have a solution that i will share by end of the week

**Comment by lucidrains** [comment]
@aamir-gmail for T5, you can just use the transformer block on the encoder side and there should be little issues (except that the coordinate descent may be a bit slow without a custom kernel)
