### ISSUE TITLE
The position embedding?

### ISSUE THREAD

**Issue by LydiaXiaohongLi** [lucidrains/CoLT5-attention#5]
Thanks for the work.
However, may I ask if the removal of position embedding is on purpose? I cannot find the place in the paper, mention the removal of position embedding in attention. In fact, the LongT5, still uses learned relative position embedding based on huggingface's implementation.

**Comment by lucidrains** [comment]
@LydiaXiaohongLi hey yes! i was going to get around to relative positional embeddings compatible with the routing of the queries and keys!

are you seeing a signal using the coordinate descent routing?

**Comment by lucidrains** [comment]
i think i will add both rotary embeddings and t5 positional bias

**Comment by lucidrains** [comment]
@LydiaXiaohongLi added rotary embeddings for starter, going to verify that it works for [mixture of attention](https://github.com/lucidrains/mixture-of-attention)

welcome you to try it

will add t5 rel pos bias at a later date

**Comment by lucidrains** [comment]
<img width="508" alt="Screen Shot 2023-06-23 at 3 00 27 PM" src="https://github.com/lucidrains/CoLT5-attention/assets/108653/b166a006-649c-423d-9774-1cb31c734b67">

slight, but noticeable effect; local attention branch already has relative positional encoding, so i think the effect of having positional encoding on the routed attention is less dramatic than usual

**Comment by LydiaXiaohongLi** [comment]
thank you! will try and let you know
